Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: false